# Generated by Django 5.2.3 on 2025-07-03 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_customer_gst_number_profile_gst_number_branchproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'role__in': ['manager', 'staff']}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile'),
        ),
    ]
