# Generated by Django 5.2.3 on 2025-07-05 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_sale_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='parent_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edits', to='dashboard.sale'),
        ),
    ]
