# Generated by Django 5.2.3 on 2025-07-05 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_sale_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edits', to='dashboard.sale'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='parent_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_sales', to='dashboard.sale'),
        ),
    ]
