# Generated by Django 5.2.3 on 2025-07-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_customer_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
